executors:
  node10:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo

version: 2.1

jobs:
  build:
    executor: node10
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: yarn

      - save_cache:
          paths:
            - node_modules
            - yarn.lock
            - ./node_modules/.cache/@shelf/elasticsearch-local
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint:ci
      - run: yarn type-check
      - run: yarn test
