executors:
  node10:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo

version: 2.1

jobs:
  build:
    executor: node10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: yarn

      - save_cache:
          paths:
            - node_modules
            - yarn.lock
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint:ci
      - run: yarn type-check

  test:
    executor: node10
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: yarn

      - save_cache:
          paths:
            - node_modules
            - yarn.lock
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint:ci
      - run: yarn type-check

      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

workflows:
  version: 2

  build_test:
    jobs:
      - build

      - test_v7:
          requires:
            - build
          steps:
            - checkout
            - attach_workspace:
                at: ~/repo

            - run: yarn test -t=7.3.0

      - test_v6:
          requires:
            - build
          steps:
            - checkout
            - attach_workspace:
                at: ~/repo

            - run: yarn test -t=6.8.2

      - test_v5:
          requires:
            - build
          steps:
            - checkout
            - attach_workspace:
                at: ~/repo

            - run: yarn test -t=5.6.16
