executors:
  node10:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo

version: 2.1

jobs:
  build:
    docker:
      - image: node:10-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: yarn

      - save_cache:
          paths:
            - node_modules
            - yarn.lock
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint
      - run: yarn type-check
      - run: yarn test
